remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Image Classification Model
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Exxienat
